server:
  port: 18081

spring:
  application:
    name: spring-ai-system
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/cms
    username: postgres
    password: 'small@123$%^'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # 开发环境使用update，生产环境用validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: Asia/Shanghai
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 5
    mongodb:
      uri: mongodb://root:sangfor!%40%23123@127.0.0.1:27017/aiChat?authSource=admin
jwt:
  secret: mySecretKeyForJWTTokenGenerationThatShouldBeLongEnoughForHS256Algorithm
  expiration: 86400
